kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: maven-web-demo
  name: maven-web-demo
spec:  
  ports:  
  - port: 8080  
    targetPort: 8080 
    name: tomcat  
  type: NodePort
  selector:  
    app: maven-web-demo
