apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: maven-web-demo
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: maven-web-demo
    spec:  
      containers:  
      - name: maven-web-demo
        image: 10.10.10.14/xiechuan/maven-web-demo:BUILD_NUMBER
        imagePullPolicy: IfNotPresent  
        ports:  
        - containerPort: 8080  
          name: tomcat 
          protocol: TCP  
